<?php

/**
 * @file
 * This file demonstrates how to use hook functions
 */

 /**
 * Implements hook_cron() 
 */
//  function hook_cron(){
//  \Drupal::messenger()->addMessage(('hey this is coming from my module'), 'status', TRUE);
//  }

/**
 * Implements hook_cron() 
 */

// function hook_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
//     if ($form_id == 'node_article_edit_form'){
//         $form['actions']['submit']['#value'] = t("Save this amazing article");
//     }
// }









?>